### ISSUE TITLE
Compilation fails due to struct comparison failures

### ISSUE THREAD

**Issue by harbaum** [emoon/fx68x_verilator#1]
This is exactly what I was looking for. But infortunately compilation fails.

I am trying this with Verilator 5.006 2023-01-22 rev (Debian 5.006-3) and g++ (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0

```
$ make -j -C obj_dir -f Vfx68k.mk && obj_dir/Vfx68k
g++  -I.  -MMD -I/usr/share/verilator/include -I/usr/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow       -Os -c -o sim_main.o sim_main.cpp
g++  -I.  -MMD -I/usr/share/verilator/include -I/usr/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow       -Os -c -o Vfx68k___024root__DepSet_haea10b53__0.o Vfx68k___024root__DepSet_haea10b53__0.cpp
g++  -I.  -MMD -I/usr/share/verilator/include -I/usr/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=0 -DVM_TRACE_FST=0 -DVM_TRACE_VCD=0 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow        -c -o Vfx68k___024root__DepSet_haea10b53__0__Slow.o Vfx68k___024root__DepSet_haea10b53__0__Slow.cpp
echo "" > Vfx68k__ALL.verilator_deplist.tmp
Vfx68k___024root__DepSet_haea10b53__0__Slow.cpp: In function ‘void Vfx68k___024root___eval_triggers__stl(Vfx68k___024root*)’:
Vfx68k___024root__DepSet_haea10b53__0__Slow.cpp:21:40: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_irdecod__struct1’ and ‘Vfx68k_s_irdecod__struct1’)
   20 |     vlSelf->__VstlTriggered.at(1U) = ((vlSelf->fx68k__DOT__Irdecod
      |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                |
      |                                                Vfx68k_s_irdecod__struct1
   21 |                                        != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Irdecod)
      |                                        ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   Vfx68k_s_irdecod__struct1
Vfx68k___024root__DepSet_haea10b53__0__Slow.cpp:23:42: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_nanod__struct3’ and ‘Vfx68k_s_nanod__struct3’)
   22 |                                       | (vlSelf->fx68k__DOT__Nanod
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  Vfx68k_s_nanod__struct3
   23 |                                          != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Nanod));
      |                                          ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     |
      |                                                     Vfx68k_s_nanod__struct3
Vfx68k___024root__DepSet_haea10b53__0__Slow.cpp:25:39: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_irdecod__struct1’ and ‘Vfx68k_s_irdecod__struct1’)
   24 |     vlSelf->__VstlTriggered.at(2U) = (vlSelf->fx68k__DOT__Irdecod
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               Vfx68k_s_irdecod__struct1
   25 |                                       != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Irdecod);
      |                                       ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  Vfx68k_s_irdecod__struct1
Vfx68k___024root__DepSet_haea10b53__0__Slow.cpp:27:39: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_nanod__struct3’ and ‘Vfx68k_s_nanod__struct3’)
   26 |     vlSelf->__VstlTriggered.at(3U) = (vlSelf->fx68k__DOT__Nanod
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               Vfx68k_s_nanod__struct3
   27 |                                       != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Nanod);
      |                                       ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  Vfx68k_s_nanod__struct3
Vfx68k___024root__DepSet_haea10b53__0.cpp: In function ‘void Vfx68k___024root___eval_triggers__act(Vfx68k___024root*)’:
Vfx68k___024root__DepSet_haea10b53__0.cpp:37:40: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_irdecod__struct1’ and ‘Vfx68k_s_irdecod__struct1’)
   36 |     vlSelf->__VactTriggered.at(0U) = ((vlSelf->fx68k__DOT__Irdecod
      |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                |
      |                                                Vfx68k_s_irdecod__struct1
   37 |                                        != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Irdecod)
      |                                        ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   Vfx68k_s_irdecod__struct1
Vfx68k___024root__DepSet_haea10b53__0.cpp:39:42: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_nanod__struct3’ and ‘Vfx68k_s_nanod__struct3’)
   38 |                                       | (vlSelf->fx68k__DOT__Nanod
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  Vfx68k_s_nanod__struct3
   39 |                                          != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Nanod));
      |                                          ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     |
      |                                                     Vfx68k_s_nanod__struct3
Vfx68k___024root__DepSet_haea10b53__0.cpp:41:39: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_irdecod__struct1’ and ‘Vfx68k_s_irdecod__struct1’)
   40 |     vlSelf->__VactTriggered.at(1U) = (vlSelf->fx68k__DOT__Irdecod
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               Vfx68k_s_irdecod__struct1
   41 |                                       != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Irdecod);
      |                                       ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  Vfx68k_s_irdecod__struct1
Vfx68k___024root__DepSet_haea10b53__0.cpp:43:39: error: no match for ‘operator!=’ (operand types are ‘Vfx68k_s_nanod__struct3’ and ‘Vfx68k_s_nanod__struct3’)
   42 |     vlSelf->__VactTriggered.at(2U) = (vlSelf->fx68k__DOT__Nanod
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               Vfx68k_s_nanod__struct3
   43 |                                       != vlSelf->__Vtrigrprev__TOP__fx68k__DOT__Nanod);
      |                                       ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  Vfx68k_s_nanod__struct3

```

**Comment by harbaum** [comment]
Works with a freshly compiled Verilator 5.015 devel rev v5.014-19-g768b78e7d

Sorry for the noise, but perhaps this hint helps someone else.

**Comment by emoon** [comment]
Cool. Hopefully you find the code useful. I haven't really documented much of it because I used it as a testbed for hacking around :)
